# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter
version:      0.50
version_from: lib/HTML/WikiConverter.pm
installdirs:  site
requires:
    HTML::Entities:                1.27
    HTML::Tree:                    3.18
    Test::More:                    0
    URI:                           1.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
